export const environment = {
  production: false,
  apiKey: 'devKey',
  apiLoginUrl: 'https://dev-api.myverkoper.com/api',
  // apiLoginUrl: 'https://qa-api.myverkoper.com/api',
  // apiLoginUrl: 'https://api.myverkoper.com/api',
  apiUrl: 'https://dev-api.myverkoper.com/api',
  // apiUrl: 'https://qa-api.myverkoper.com/api',
  // apiUrl: 'https://api.myverkoper.com/api',
  firebaseURL: '/ChatModuleDev',
  // firebaseURL: '/ChatModuleTest',
  firebaseAssistURL: '/AssistModuleDev',
  // firebaseAssistURL: '/AssistModuleTest',
  sellerUrl: 'https://dev-seller.myverkoper.com',
  security_token:'',
  firebase: {
    apiKey: "AIzaSyDiqCiiTs-aI5Amg_8cDJ0GAQ9htVUDqGY",
    authDomain: "myverkoperlivev1.firebaseapp.com",
    databaseURL: "https://myverkoperlivev1-default-rtdb.firebaseio.com",
    projectId: "myverkoperlivev1",
    storageBucket: "myverkoperlivev1.appspot.com",
    messagingSenderId: "587126445002",
    appId: "1:587126445002:web:02f76eeba25a760925b533",
    measurementId: "G-EF1TERP8BD",
    vapidKey: "BD32cX5kUOoV9u_PylY7in_TTC6aQyhuDmYo88UgEKR0g6F9jkZpqdzfY60Ojc6ilAeH9v93O6OxhhDX7hDY1yU",
    facebook_app_id: "1522385301591861",
    fb_login_protocol_scheme: "fb1522385301591861",
    facebook_client_token: "1915fe0e0c8dd90ee08dbefbbf763511"
  },
   key: '$2a$10$9hVJ2em49Sz6MbXhn6/4i.zYp.86fhWJ81C7SYufcifiJjUTQDJae',
  // key: 'eyJpdiI6ImtvQzhKSXNXcnhzZ3I3NzRibzJMcUE9PSIsInZhbHVlIjoiYmJOOUdqeEZzN1hQeVZGQXBRWXgwNWFwME5wVmxxOW94T0ZpUTZFN3g0cz0iLCJtYWMiOiJkNWUyNjRjYzVjYjQxMTYwN2JlYzA3ZTBhODM0OGQxMGRlODdmMzk5OTE4NmEzOTM2MTllZTYxYzQxYmZiOGNlIiwidGFnIjoiIn0=',
  //  key: 'eyJpdiI6Im16WURtODhwK3BWR0Jxd09haXYyUGc9PSIsInZhbHVlIjoiKzJMdGxsYmI3OCtmRmlqUlNHakFCd3RCc05mZlBVb2JIRUx5UVlPS2FVTT0iLCJtYWMiOiIzY2Y3NGZhMGY3OTk5ZWMwZjQyNGFhOWM2ZTU2MDYzNWRmNjM5NWEyMjcwM2IyNzdmZTkxYjE4NDFhZmQ1NDMyIiwidGFnIjoiIn0=',
  version: "2.0.1"
};